# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14zJ6T_WfGEFjKoTvrnY7gpH-ZPEHYtxd
"""

username = input("Enter your username: ")
print("Your username is: ", username)

num1 = input("Enter the first number: ")
num2 = input("Enter the second number: ")
sum = float (num1) + float (num2)
print("The total is: ", sum)